const fs = require('fs');
const { PdfDocument, tokenizeContent } = require('@fitfak/pdf-doc');
const { collectGraphics } = require('@fitfak/pdf-scene/src/import/pdfgraphics');
const doc = PdfDocument.load(fs.readFileSync('/home/user/pdf/.tmp/kaynak.pdf'));
const geo = doc.getPageGeometry(0);
const content = doc.getPageContent(0);
console.log(content.toString('latin1').slice(0, 600));
const page = doc.getPage(0);
const res = doc.resolve(doc.getPageProperty(page, 'Resources'));
console.log('Resources:', res && [...res.map.keys()]);
const xo = doc.resolve(doc.get(res, 'XObject'));
console.log('XObject:', xo && [...xo.map.keys()]);
const { records, warnings } = collectGraphics(doc, 0, geo);
console.log('kayıtlar:', records.map(r => r.kind), warnings);
